import { expect, test } from '@playwright/test'
import { expectNoAxeViolations } from './support/accessibility'
import { installBrowserGuards, openPersonaResults } from './support/browserGuards'

test('Secret Shared Disclosure stays in the fragment, removes it after capture, and opens locally', async ({ page }) => {
  const guards = await installBrowserGuards(page)
  await openPersonaResults(page, 'balanced-authority-pattern')
  await expect(page.locator('.current-role-cards-grid h3').first()).toBeVisible()
  const expectedRoles = await page.locator('.current-role-cards-grid h3').allTextContents()
  await page.getByRole('button', { name: 'Create my role cards' }).click()
  const dialog = page.getByRole('dialog', { name: 'Export & Share' })
  await dialog.getByRole('button', { name: /Encrypted Disclosure/i }).click()
  await expect(dialog.getByRole('checkbox', { name: /Current Role Set/i })).toBeChecked()
  await expect(dialog.getByRole('checkbox', { name: /Role definitions/i })).toBeChecked()
  await expect(dialog.getByRole('group', { name: 'Include in the encrypted disclosure' }).getByRole('checkbox')).toHaveCount(2)
  await dialog.getByRole('button', { name: 'Create encrypted disclosure' }).click()
  const artifact = {
    link: await dialog.getByLabel('Encrypted Capsule link').inputValue(),
    serializedEnvelope: await dialog.getByLabel('Encrypted Capsule text').inputValue(),
    secret: await dialog.getByLabel(/Secret — never embedded in the link/i).inputValue(),
  }
  await expectNoAxeViolations(page, 'Secret Shared Disclosure output')

  expect(artifact.link).not.toContain(artifact.secret)
  expect(artifact.serializedEnvelope).not.toContain(artifact.secret)
  expect(new URL(artifact.link).pathname).toBe('/capsule')
  expect(new URL(artifact.link).search).toBe('')
  expect(new URL(artifact.link).hash).toMatch(/^#capsule=/)

  const documentRequests: string[] = []
  page.on('request', (request) => { if (request.isNavigationRequest()) documentRequests.push(request.url()) })
  await page.goto(artifact.link)
  await expect(page).toHaveURL(/\/capsule$/)
  expect(new URL(documentRequests.at(-1)!).hash).toBe('')
  expect(new URL(documentRequests.at(-1)!).search).toBe('')
  await expect(page.getByLabel('Encrypted Capsule text')).toHaveValue(artifact.serializedEnvelope)
  await expect(page.locator('meta[name="robots"]')).toHaveAttribute('content', 'noindex, nofollow')
  await expect(page.locator('link[rel="canonical"]')).toHaveCount(0)

  await page.getByLabel('Separately shared secret').fill('KA1-wrong.secret')
  await page.getByRole('button', { name: 'Unlock Capsule' }).click()
  await expect(page.getByText(/could not be unlocked/)).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Shared Role Set' })).toHaveCount(0)
  await page.getByLabel('Separately shared secret').fill(artifact.secret)
  await page.getByRole('button', { name: 'Unlock Capsule' }).click()
  await expect(page.getByRole('heading', { name: 'Shared Role Set' })).toBeVisible()
  expect(await page.locator('.historical-role-list > li > strong').allTextContents()).toEqual(expectedRoles)
  await expect(page.locator('.historical-role-list > li > p')).toHaveCount(expectedRoles.length)
  await expect(page.getByRole('heading', { name: 'Privacy receipt' })).toBeVisible()
  await expect(page.getByText('Raw assessment answers')).toBeVisible()
  await expectNoAxeViolations(page, 'Unlocked Secret Shared Disclosure')
  await guards.assertClean()
})

test('Private Restore export requires file, secret, preview, and explicit confirmation', async ({ browser }) => {
  const context = await browser.newContext()
  const exportPage = await context.newPage()
  const exportGuards = await installBrowserGuards(exportPage)
  await openPersonaResults(exportPage, 'balanced-authority-pattern')
  await expect(exportPage.locator('.current-role-cards-grid h3').first()).toBeVisible()
  const exportedRoles = await exportPage.locator('.current-role-cards-grid h3').allTextContents()
  const exportedDiscovery = await exportPage.locator('.role-grid > .role-card h3').allTextContents()
  await exportPage.getByRole('link', { name: 'Create a Private Restore backup' }).click()
  await expect(exportPage).toHaveURL(/\/restore$/)
  await expect(exportPage.locator('meta[name="robots"]')).toHaveAttribute('content', 'noindex, nofollow')
  await exportPage.getByRole('button', { name: 'Create encrypted restore' }).click()
  const secret = await exportPage.getByLabel('Generated restore secret').locator('code').innerText()
  const downloadPromise = exportPage.waitForEvent('download')
  await exportPage.getByRole('button', { name: 'Download restore file' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('kinkatlas-private-restore.kinkatlas-restore')
  const restorePath = await download.path()
  expect(restorePath).toBeTruthy()
  await exportGuards.assertClean()

  const importPage = await context.newPage()
  const importGuards = await installBrowserGuards(importPage)
  await openPersonaResults(importPage, 'multiple-hard-limits-pattern')
  await expect(importPage.locator('.current-role-cards-grid h3').first()).toBeVisible()
  const existingRoles = await importPage.locator('.current-role-cards-grid h3').allTextContents()
  await importPage.getByRole('link', { name: 'Create a Private Restore backup' }).click()
  await importPage.getByRole('button', { name: 'Private Restore file', exact: true }).setInputFiles(restorePath!)
  await expect(importPage.getByText(/Encrypted file validated/)).toBeVisible()
  await importPage.getByLabel('Restore secret').fill('KA1-wrong.secret')
  await importPage.getByRole('button', { name: 'Unlock preview' }).click()
  await expect(importPage.getByText(/could not be unlocked/)).toBeVisible()
  await expect(importPage.getByRole('heading', { name: 'Restore preview' })).toHaveCount(0)
  await importPage.getByLabel('Restore secret').fill(secret)
  await importPage.getByRole('button', { name: 'Unlock preview' }).click()
  await expect(importPage.getByRole('heading', { name: 'Restore preview' })).toBeFocused()
  await expectNoAxeViolations(importPage, 'Private Restore confirmation preview')
  await expect(importPage.getByText(/Historical result included/)).toBeVisible()
  await expect(importPage.getByRole('heading', { name: 'Your saved KinkAtlas result' })).toHaveCount(0)
  await importPage.getByRole('button', { name: 'Cancel' }).click()
  await expect(importPage.getByRole('heading', { name: 'Restore preview' })).toHaveCount(0)
  await importPage.goBack()
  await expect(importPage.getByRole('heading', { name: 'A map, not a verdict.' })).toBeVisible()
  expect(await importPage.locator('.current-role-cards-grid h3').allTextContents()).toEqual(existingRoles)

  await importPage.getByRole('link', { name: 'Create a Private Restore backup' }).click()
  await importPage.getByRole('button', { name: 'Private Restore file', exact: true }).setInputFiles(restorePath!)
  await importPage.getByLabel('Restore secret').fill(secret)
  await importPage.getByRole('button', { name: 'Unlock preview' }).click()
  await expect(importPage.getByRole('heading', { name: 'Restore preview' })).toBeFocused()
  await importPage.getByRole('button', { name: 'Confirm restore' }).click()
  await expect(importPage.getByText(/Restore complete/)).toBeVisible()
  await expect(importPage.getByRole('heading', { name: 'Your saved KinkAtlas result' })).toBeVisible()
  expect(await importPage.locator('.historical-role-list > li > strong').allTextContents()).toEqual(exportedRoles)
  await expect(importPage.locator('link[rel="canonical"]')).toHaveCount(0)
  await importPage.goBack()
  await expect(importPage.getByRole('heading', { name: 'A map, not a verdict.' })).toBeVisible()
  expect(await importPage.locator('.current-role-cards-grid h3').allTextContents()).toEqual(exportedRoles)
  expect(await importPage.locator('.role-grid > .role-card h3').allTextContents()).toEqual(exportedDiscovery)
  await importGuards.assertClean()
  await context.close()
})
